import React, { useState, useEffect } from "react";
import { initializeApp } from "firebase/app";
import { getFirestore, enableIndexedDbPersistence } from "firebase/firestore";
import { getDatabase, ref, push, onChildAdded, query, orderByChild, limitToLast } from "firebase/database";

const firebaseConfig = { apiKey:"AIzaSyDUMMY", authDomain:"tycoon-empire-world.firebaseapp.com", databaseURL:"https://tycoon-empire-world-default-rtdb.firebaseio.com", projectId:"tycoon-empire-world", storageBucket:"tycoon-empire-world.appspot.com", messagingSenderId:"123456789", appId:"1:123456789:web:omerta" };
const fbApp = initializeApp(firebaseConfig);
const db = getFirestore(fbApp);
const rtdb = getDatabase(fbApp);
try{ enableIndexedDbPersistence(db); }catch(e){}
const ID = { id:localStorage.getItem("omerta_id")||"OM-"+Math.random().toString(36).slice(2,6).toUpperCase(), name:localStorage.getItem("omerta_name")||"DON_V" };
localStorage.setItem("omerta_id",ID.id); localStorage.setItem("omerta_name",ID.name);

export default function App(){
  const [open,setOpen]=useState(false);
  const [pin,setPin]=useState("");
  const [tab,setTab]=useState("vault");
  const [cash,setCash]=useState(5240000);
  const [chat,setChat]=useState([]);
  const [chatInput,setChatInput]=useState("");
  const [board] = useState([
    {r:1,n:ID.name,f:"🇰🇪",c:"KE",w:12450000,l:42,me:true},
    {r:2,n:"Vincenzo Romano",f:"🇮🇹",c:"IT",w:11200000,l:40},
    {r:3,n:"El Chapo Jr",f:"🇲🇽",c:"MX",w:9800000,l:38},
    {r:4,n:"Kazimir Volkov",f:"🇷🇺",c:"RU",w:8700000,l:35},
  ]);
  useEffect(()=>{
    try{
      const q = query(ref(rtdb,"omerta_chat"), orderByChild("timestamp"), limitToLast(50));
      return onChildAdded(q, s=>{ const v=s.val(); if(v) setChat(p=>[...p.slice(-49),v]); });
    }catch(e){}
  },[]);
  const GOLD="#D4AF37";
  return (
    <div style={{width:"100vw",height:"100vh",position:"fixed",inset:0,background:"#000",color:"#fff",overflow:"hidden",fontFamily:"Inter,system-ui"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@700;900&display=swap');*{margin:0;padding:0;box-sizing:border-box}::-webkit-scrollbar{display:none}`}</style>
      <div style={{position:"absolute",inset:0,opacity:open?1:0,pointerEvents:open?"auto":"none",transition:"0.8s 0.6s",display:"flex",flexDirection:"column",background:"#000"}}>
        <div style={{height:56,background:"#0A0A0A",borderBottom:`2px solid ${GOLD}`,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 16px"}}>
          <div style={{fontFamily:"Cinzel",fontWeight:900,color:GOLD,letterSpacing:2}}>O • OMERTA 🗡</div>
          <div style={{background:"#111",border:`1px solid ${GOLD}`,padding:"4px 10px",fontSize:11,fontWeight:700}}>${(cash/1e6).toFixed(2)}M</div>
        </div>
        <div style={{flex:1,overflowY:"auto"}}>
          {tab==="vault"&&(<div><div style={{background:"linear-gradient(180deg,#0A0A0A,#000)",borderBottom:`1px solid ${GOLD}`,padding:20}}><div style={{fontSize:10,color:"#666",letterSpacing:4}}>O DAGGER EDITION</div><div style={{fontFamily:"Cinzel",fontSize:28,fontWeight:900,color:GOLD,marginTop:6}}>GOLDEN VAULT OPEN</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginTop:16}}>{[{k:"NET WORTH",v:"$12.4M"},{k:"TERRITORY",v:"62%"},{k:"RANK",v:"#1 DON"}].map(s=><div key={s.k} style={{background:"#111",border:`1px solid ${GOLD}`,padding:12}}><div style={{fontSize:9,color:"#666"}}>{s.k}</div><div style={{fontSize:16,fontWeight:900,color:GOLD,marginTop:4}}>{s.v}</div></div>)}</div></div><div style={{padding:16}}><div style={{fontWeight:900,fontSize:13}}>🏆 GLOBAL FORBES</div><div style={{marginTop:12,background:"#0A0A0A",border:"1px solid #222"}}>{board.map(e=><div key={e.r} style={{height:64,display:"flex",alignItems:"center",padding:"0 14px",borderBottom:"1px solid #1A1A1A",background:e.me?"#1A1600":""}}><div style={{width:36,fontWeight:900,color:GOLD}}>#{e.r}</div><div style={{width:28}}>{e.f}</div><div style={{flex:1}}><div style={{fontWeight:700,fontSize:13}}>{e.n}</div><div style={{fontSize:10,color:"#666"}}>{e.c} Lvl {e.l}</div></div><div style={{color:"#4CAF50",fontWeight:900}}>${(e.w/1e6).toFixed(1)}M</div></div>)}</div></div><div style={{margin:"0 16px",background:"#8B0000",border:"3px solid #FF0000",padding:14,display:"flex",gap:12}}><div style={{fontSize:28}}>🚨</div><div><div style={{fontWeight:900}}>FBI FILE #{ID.id}</div><div style={{fontSize:11,marginTop:6}}>NAME: {ID.name.toUpperCase()}<br/>REWARD: $500K • DOCKS #14</div></div></div><div style={{marginTop:16,background:"#0A0A0A",borderTop:"1px solid #222"}}><div style={{padding:"10px 16px",fontWeight:900,fontSize:11,background:"#111"}}>💬 WORLD WIRE</div><div style={{height:120,overflowY:"auto",padding:12,fontSize:12}}>{chat.length===0?<span style={{color:"#444"}}>Be first DON</span>:chat.map((c,i)=><div key={i}><span style={{color:GOLD}}>{c.flag} {c.username}:</span> {c.text}</div>)}</div><div style={{display:"flex",borderTop:"1px solid #222"}}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Broadcast..." style={{flex:1,background:"#000",color:"#fff",border:"none",padding:14}}/><button onClick={()=>{if(chatInput.trim()){push(ref(rtdb,"omerta_chat"),{username:ID.name,flag:"🇰🇪",text:chatInput.trim(),timestamp:Date.now()});setChatInput("");}}} style={{background:GOLD,color:"#000",border:"none",padding:"0 20px",fontWeight:900}}>SEND</button></div></div></div>)}
          {tab==="items"&&(<div><div style={{height:220,background:"url(/luxury_mafia_item_cards.webp) center/cover",borderBottom:`2px solid ${GOLD}`,position:"relative"}}><div style={{position:"absolute",inset:0,background:"linear-gradient(0deg,#000 0%,transparent 60%)"}}/><div style={{position:"absolute",bottom:16,left:16}}><div style={{background:GOLD,color:"#000",padding:"4px 8px",fontSize:10,fontWeight:900}}>LEGENDARY</div><div style={{fontFamily:"Cinzel",fontSize:22,fontWeight:900,marginTop:8}}>MAFIA ITEMS</div></div></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:1,background:"#222"}}>{[{n:"Casino Chip",i:"🎰",p:500},{n:"Gold Pistol",i:"🔫",p:2500},{n:"Briefcase",i:"💼",p:10000},{n:"Gold Watch",i:"⌚",p:3500},{n:"Whiskey",i:"🥃",p:800},{n:"Sports Car",i:"🏎️",p:50000}].map(it=><div key={it.n} style={{background:"#0A0A0A",padding:18,textAlign:"center"}}><div style={{fontSize:42}}>{it.i}</div><div style={{fontWeight:900,fontSize:13,marginTop:6}}>{it.n}</div><div style={{color:GOLD,fontWeight:900,marginTop:4}}>${it.p.toLocaleString()}</div><button onClick={()=>setCash(c=>c-it.p)} style={{marginTop:8,width:"100%",background:GOLD,color:"#000",border:"none",padding:8,fontWeight:900,fontSize:11}}>BUY</button></div>)}</div></div>)}
          {tab==="map"&&(<div><div style={{height:240,background:"url(/omerta_territory_map_cards.webp) center/cover",borderBottom:`2px solid ${GOLD}`,position:"relative"}}><div style={{position:"absolute",inset:0,background:"linear-gradient(0deg,#000 80%,transparent)"}}/><div style={{position:"absolute",bottom:16,left:16}}><div style={{fontFamily:"Cinzel",fontSize:20,fontWeight:900}}>TERRITORY MAP</div><div style={{fontSize:11,color:"#aaa",marginTop:4}}>6 DISTRICTS</div></div></div>{[{n:"UPTOWN - Casino",c:45},{n:"DOWNTOWN - Nightclub",c:62},{n:"DOCKS - Warehouse",c:80},{n:"LITTLE ITALY",c:55},{n:"MIDTOWN - Bank",c:20},{n:"CHINATOWN",c:30}].map(d=><div key={d.n} style={{height:72,background:"#0A0A0A",borderBottom:"1px solid #1A1A1A",display:"flex",alignItems:"center",padding:"0 16px",gap:14}}><div style={{width:44,height:44,background:"#111",border:`1px solid ${GOLD}`,display:"grid",placeItems:"center"}}>📍</div><div style={{flex:1}}><div style={{fontWeight:900,fontSize:13}}>{d.n}</div><div style={{marginTop:6,height:4,background:"#222"}}><div style={{height:4,background:GOLD,width:`${d.c}%`}}/></div></div><div style={{color:GOLD,fontWeight:900}}>{d.c}%</div></div>)}</div>)}
          {tab==="profile"&&(<div style={{padding:20,background:"radial-gradient(ellipse at top,#1A1600,#000)",minHeight:"100vh",borderTop:`4px solid ${GOLD}`}}><div style={{border:`2px solid ${GOLD}`,background:"#0A0A0A"}}><div style={{background:GOLD,color:"#000",padding:"10px 16px",fontWeight:900,fontSize:12,display:"flex",justifyContent:"space-between"}}><span>🗡 OMERTA PASSPORT</span><span>O-DAGGER</span></div><div style={{padding:20,display:"flex",gap:16}}><div style={{width:80,height:80,background:"#111",border:`2px solid ${GOLD}`,display:"grid",placeItems:"center",fontSize:36}}>🗡</div><div><div style={{fontFamily:"Cinzel",fontSize:20,fontWeight:900}}>{ID.name.toUpperCase()}</div><div style={{color:GOLD,fontSize:12,marginTop:4}}>★ DON • LEVEL 42 • {ID.id}</div></div></div></div></div>)}
        </div>
        <div style={{height:64,background:"#0A0A0A",borderTop:`2px solid ${GOLD}`,display:"flex"}}>{[{id:"vault",icon:"💰",l:"VAULT"},{id:"items",icon:"🎴",l:"ITEMS"},{id:"map",icon:"🗺",l:"MAP"},{id:"profile",icon:"🪪",l:"PROFILE"}].map(t=><button key={t.id} onClick={()=>setTab(t.id)} style={{flex:1,background:tab===t.id?"#1A1600":"transparent",border:"none",color:tab===t.id?GOLD:"#666",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:20}}>{t.icon}</span><span style={{fontSize:9,fontWeight:900}}>{t.l}</span></button>)}</div>
      </div>
      <div style={{position:"absolute",inset:0,background:"#000",zIndex:30,transformOrigin:"left",transform:open?"rotateY(-105deg)":"rotateY(0deg)",transition:"1.3s cubic-bezier(0.77,0,0.175,1)",display:"flex",flexDirection:"column"}}><div style={{flex:1,background:"radial-gradient(ellipse at center,#1A1A1A,#000)",borderRight:`16px solid ${GOLD}`,padding:24,display:"flex",flexDirection:"column"}}><div style={{border:`2px solid ${GOLD}`,background:"#0A0A0A",padding:14,textAlign:"center"}}><div style={{fontFamily:"Cinzel",fontSize:32,fontWeight:900,color:GOLD,letterSpacing:6}}>O • OMERTA</div><div style={{fontSize:10,color:"#666",letterSpacing:4,marginTop:6}}>O DAGGER EDITION • FULL SCREEN</div></div><div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><div onClick={()=>setOpen(true)} style={{width:120,height:120,borderRadius:"50%",background:"#1A1A1A",border:`3px solid ${GOLD}`,display:"grid",placeItems:"center",fontSize:48,cursor:"pointer",boxShadow:"0 0 40px rgba(212,175,55,0.3)"}}>🗡</div><div style={{marginTop:16,color:GOLD,fontWeight:900,letterSpacing:3,fontSize:12}}>TOUCH TO UNLOCK</div><input value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN ••••" style={{marginTop:32,width:"100%",background:"#000",border:`1px solid ${GOLD}`,color:"#fff",padding:16,textAlign:"center",letterSpacing:8}}/><button onClick={()=>setOpen(true)} style={{marginTop:12,width:"100%",background:GOLD,color:"#000",border:"none",padding:18,fontWeight:900,fontSize:15}}>🗡 UNLOCK VAULT</button></div></div></div>
      <div style={{position:"absolute",right:0,top:0,bottom:0,width:16,background:GOLD,zIndex:31,transformOrigin:"right",transform:open?"rotateY(105deg)":"rotateY(0deg)",transition:"1.3s"}}/>
    </div>
  );
     }
